# Test Node JS Application before deploy

trigger:
  - main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    node_12_x:
      node_version: 12.x

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node JS'

  - script: |
      yarn install
      yarn test:ci
    displayName: 'yarn install and running test'

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/test-report.xml'
      failTaskOnFailedTests: true
