# Test Node JS Application before deploy

trigger:
  - main

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    node_12_x:
      node_version: 12.x

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(node_version)
    displayName: 'Install Node JS'

  - script: |
      yarn install
      yarn test:ci
      yarn test:coverage
    displayName: 'yarn install, test and coverage test'

  - task: PublishTestResults@2
    inputs:
      testRunner: JUnit
      testResultsFiles: '**/test-report.xml'
      failTaskOnFailedTests: true
    displayName: 'Test Result'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/cobertura-coverage.xml'
      reportDirectory: '$(System.DefaultWorkingDirectory)/**/coverage'
    displayName: 'Publish Code Coverage'
